apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: example-worker-app

spec:
  containers:
    - name: worker-app
      image: prabhavagrawal/worker-app
      ports:
        - containerPort: 80
